export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const OTP_SUCCESS = 'OTP_SUCCESS';
export const OTP_FAIL = 'OTP_FAIL';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const CREATE_LOSTITEM_SUCCESS = 'CREATE_LOSTITEM_SUCCESS';
export const CREATE_LOSTITEM_FAIL = 'CREATE_LOSTITEM_FAIL';
export const CREATE_LOSTITEM_LOADING = 'CREATE_LOSTITEM_LOADING';

export const CREATE_FOUNDITEM_SUCCESS = 'CREATE_FOUNDITEM_SUCCESS';
export const CREATE_FOUNDITEM_FAIL = 'CREATE_FOUNDITEM_FAIL';
export const CREATE_FOUNDITEM_LOADING = 'CREATE_FOUNDITEM_LOADING';